version: '3.5'
services:
  medicinedb-front:
    container_name: medicinedb-front
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true